eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      #defaultZone: https://service-registry-dev.azurewebsites.net:443/eureka
      defaultZone: http://localhost:443/eureka
  instance:
    #hostname: service-registry-dev.azurewebsites.net
    hostname: localhost
    secure-port-enabled: false
    nonsecure-port-enabled: true
    nonSecurePort: 80
    securePort: 443
    instanceId: ${eureka.instance.hostname}:${spring.application.name}:443
    statusPageUrl: https://${eureka.hostname}:443/actuator/info
    healthCheckUrl: https://${eureka.hostname}:443/actuator/health
    secureHealthCheckUrl: https://${eureka.hostname}:443/actuator/health    
    
    
microservice:
  user-service-dev:
    endpoints:
      endpoint:
        uri: http://USER-SERVICE/
  transaction-service-dev:
    endpoints:
      endpoint:
        uri: http://TRANSACTION-SERVICE/   
