eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: https://service-registry-dev.azurewebsites.net:8761/eureka
  instance:
    hostname: service-registry-dev.azurewebsites.net
    secure-port-enabled: true
    nonsecure-port-enabled: false
    nonSecurePort: 80
    securePort: 8761
    instanceId: ${eureka.instance.hostname}:${spring.application.name}:8761
    statusPageUrl: https://${eureka.hostname}:8761/actuator/info
    healthCheckUrl: https://${eureka.hostname}:8761/actuator/health
    secureHealthCheckUrl: https://${eureka.hostname}:8761/actuator/health
    
    
microservice:
  user-service-dev:
    endpoints:
      endpoint:
        uri: http://USER-SERVICE/
  transaction-service-dev:
    endpoints:
      endpoint:
        uri: http://TRANSACTION-SERVICE/   
